repos:

#- repo: https://github.com/psf/black
#  rev: 20.8b1
#  hooks:
#  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=3000']
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

#- repo: https://github.com/PyCQA/isort
#  rev: 5.7.0
#  hooks:
#  - id: isort

- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.4
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]

#- repo: https://github.com/pycqa/flake8
#  rev: 3.8.4
#  hooks:
#  - id: flake8
#    exclude: docs/conf.py
#    additional_dependencies: [flake8-bugbear, flake8-print]
#
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.800
#  hooks:
#  - id: mypy
#    files: src

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
