// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-json-importer/src/plugins');
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/MDF');







// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'SetStateFromJSON': 'node_modules/webgme-json-importer/src/plugins/SetStateFromJSON',
  'ExportToJSON': 'node_modules/webgme-json-importer/src/plugins/ExportToJSON',
  'webgme-json-importer': './node_modules/webgme-json-importer/src/common',
  'mdf_gme': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/mdf_gme';
validateConfig(config);
module.exports = config;
